### ISSUE TITLE
Architecture Proposal for Multi Cluster Listener

### ISSUE THREAD

**Issue by n3rdc4ptn** [openmfp/kubernetes-graphql-gateway#149]
I want to propose the following concept for a multi cluster listener feature, where the cluster access is defined in a special resource.

## Problem

We want to provide the listener with a list of MCPs which are scanned and listened to. The listener needs to have access to these clusters. As handling this using a special implementation for MCP is very complex and too specific, I'd like to propose a more generic approach.

## Solution

A custom resource the listener defines which provides the listener with all informations needed for scanning a cluster.
We could also provide not only authentication details but also some filter options to blacklist some resources which are then not put into the API schema.

### Resource

```yaml
apiVersion: gateway.openmfp.org/v1alpha1
kind: ClusterAccess
metadata:
  name: my-cluster-access
spec:
  path: kubernetes # optional, if not set, the name of the resource is used
  host: https://my-cluster.com
  ca:
    secretRef:
      name: ca-secret
      namespace:
      key:
    # or
    configMapRef:
      # ...
  auth:
    secretRef:
        name: my-secret
        namespace: my-namespace
        key: token
    # or
    kubeconfigSecretRef:
        name: my-kubeconfig
    # or
    serviceAccount: my-service-account # optional, if not set, the default service account is used

  # STRETCH
  filterResources:
    allowlist:
        - apiVersion: v1
          kind: Secret
    # or
    denylist:
        - apiVersion: v1
          kind: Secret # optional so we could also allow just one apiVersion
        # or with wildcard / regex
        - apiVersion: v1
          kind: ".*"

  # STRETCH: Configure the gateway behaviour through the cluster access;
  # maybe through a separate config file which is shared or the gateway can also read the Resource
  gateway:
    impersonate: false # optional, if true, the gateway will use the ENV variable setting
    shouldUseServiceAccount: false # optional, if true, the gateway will use the service account of the pod
```

### API Definitions

Still be in the shared volume between the containers, as files. Maybe also adding a config file for every cluster for the gateway to get information. But thats discussable and stretch.
